language = "C"

[export]

item_types = [
  "functions",
  "enums",
  "opaque",
  "structs",
]

include = [
  "Header",
  "Endian",
  "ByteJumpOption",
  "CFlowbits",
  "ElementTag",
]

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
